app/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='homr'),
    path('index/', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('signup/', views.account_signup, name='signup'),
    path('login/', views.account_login, name='login'),
    path('logout/', views.account_logout, name='logout'),
    path('info/', views.account_info, name="info"),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('cancel/<int:id>/', views.cancel, name='cancel'),
    path('is_scheduled/<int:id>/', views.is_schedule, name='is_scheduled'),
    path('clinics/', include('clinics.urls', namespace='clinics')),
    # <TR> Used so I can pull up the clinics page for debugging purposes
]

clinics/urls.py
from django.urls import path

from . import views

app_name = 'clinics'
urlpatterns = [
    path('search', views.clinics_search, name='search'),
    path('detail/<str:clinic_id>', views.clinics_detail, name='clinics_detail'),
    path('insert/<int:n_records>', views.clinics_bulk_insert, name='insert'),
    path('<int:clinic_id>/schedule/', views.clinic_schedule, name='clinic_schedule'),
    path('<int:sched_id>/schedule_appt/', views.schedule_appt, name='sched_appt'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('clinics/', include('clinics.urls'))
]

templates/users/edit.html
{% extends "base.html" %}
{% load i18n %}
{#{% load account socialaccount %}#}
{#{% load crispy_forms_tags %}#}

{% block head_title %}{% trans "edit" %}{% endblock %}

{% block content %}
    <main style="height: 80%">
        <div class="container">
            <section class="mb-4">
                <div class="row wow fadeIn">
                    <div class='col-6 offset-3'>
                        <h1>{% trans "edit" %}</h1>
                        {% if request.user.is_authenticated %}
                            <form class="signup" method="POST" action="{% url 'edit' user.id %}">{% csrf_token %}
                                <div class="mb-3">
                                    <label for="signupInputUsername" class="form-label">Username</label>
                                    <input name="username" type="input" class="form-control" id="signupInputUsername" placeholder="{{ user.username }}">
                                </div>
                                <div class="mb-3">
                                    <label for="signupInputEmail" class="form-label">Email address</label>
                                    <input name="email" type="email" class="form-control has-validation"
                                           id="signupInputEmail"
                                           aria-describedby="emailHelp" placeholder="{{ user.email }}">
                                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="signupInputPhone" class="form-label">Phone</label>
                                    <input name="phone" type="tel" class="form-control" id="signupInputPhone"
                                           aria-describedby="phoneHelp" placeholder="{{ user.profile.phone }}">
                                    <div id="phoneHelp" class="form-text">We'll never share your phone with anyone else.
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="signupInputPwd" class="form-label">Password</label>
                                    <input name="password" type="password" class="form-control" id="signupInputPwd">
                                </div>
                                <button class="btn btn-primary" type="submit">{% trans "edit" %}</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </section>
        </div>
    </main>

{% endblock %}

templates/users/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            {% csrf_token %}
            <br>
            <div class="col-md-4"> error: {{ message }}</div>
        </div>
    </div>
    {% if request.user.is_authenticated %}
    <form class="clinics" method="GET" action="{% url 'clinics:search' %}">{% csrf_token %}
        <button class="btn btn-primary" type="submit">clinics search</button>
    </form>
    {% endif %}
</div>
{% endblock content %}

templates/users/info.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en-US">
    <head>
        <meta charset="UTF-8"/>
        <meta
                name="viewport"
                content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
        />
        <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
        <meta name="Referrer" content="origin"/>
        <title>Clinics</title>
        <link
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
                rel="stylesheet"
                crossorigin="anonymous"
        />
        <link href="{% static 'css/clinics-style.css' %}" rel="stylesheet"/>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
        <script
                src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
                crossorigin="anonymous"
        ></script>
    </head>
    <body>
    <div class="top">
        <div class="container" style="padding: 30px 0">
            <div class="row g-3">
                {% if user.is_authenticated %}
                    <div class="col-sm-6 col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <nobr><h5 class="card-title">username : {{ user.username }}</h5></nobr>
                                <nobr><h5 class="card-title">email : {{ user.email }}</h5></nobr>
                                <nobr><h5 class="card-title">phone: {{ user.profile.phone }}</h5></nobr>
                                <nobr><a href="{% url 'edit' user.id %}" class="btn btn-primary">edit</a></nobr>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="body">
        <div class="content container" style="padding: 30px 0">
            <div class="row g-3">
                {% if user.is_authenticated %}
                    {% for appoint in appoints %}
                        <div class="col-sm-6 col-md-4">
                            <div class="card">
                                <img
                                        src="{{ appoint.pic_address }}"
                                        class="card-img-top"
                                />
                                <div class="card-body">
                                    <h5 class="card-title">{{ appoint.name }}</h5>
                                    <h5 class="card-title">{{ appoint.address }}, {{ appoint.city }}, {{ appoint.state }}, {{ appoint.zip_code }}</h5>
                                    <h5 class="card-title">{{ appoint.start_time }}</h5>
                                    <a href="{% url 'cancel' appoint.id %}" class="btn btn-primary">Cancel</a>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <h2>No appointment has been booked yet</h2>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="footer">
        <div>©️ 2021 Clinics Team</div>
    </div>
</body>
</html>
{% endblock content %}

templates/users/login.html
{% extends "base.html" %}
{% load i18n %}
{#{% load account socialaccount %}#}
{#{% load crispy_forms_tags %}#}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
    <main style="height: 80%">
        <div class="container">
            <section class="mb-4">
                <div class="row wow fadeIn">
                    <div class='col-6 offset-3'>
                        <h1>{% trans "Login" %}</h1>
                        {% if request.user.is_authenticated %}
                            <p>You have logged in out system.</p>
                        {% else %}
                            <form class="login" method="POST" action="{% url 'login' %}">{% csrf_token %}
                                <div class="mb-3">
                                    <label for="loginInputUsername" class="form-label">Username</label>
                                    <input name="username" type="input" class="form-control" id="loginInputUsername">
                                </div>
                                <div class="mb-3">
                                    <label for="loginInputPwd" class="form-label">Password</label>
                                    <input name="password" type="password" class="form-control" id="loginInputPwd">
                                </div>
                                <button class="btn btn-primary" type="submit">{% trans "Login" %}</button>
                            </form>                        {% endif %}
                    </div>
                </div>
            </section>
        </div>
    </main>

{% endblock %}

templates/users/logout.html
{% extends "base.html" %}
{% load i18n %}
{#{% load account socialaccount %}#}
{#{% load crispy_forms_tags %}#}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
    <main style="height: 80%">
        <div class="container">
            <section class="mb-4">
                <div class="row wow fadeIn">
                    <div class='col-6 offset-3'>
                        <h1>{% trans "Login" %}</h1>
                        {% if request.user.is_authenticated %}
                            <p>Logout failed.</p>
                        {% else %}
                            <p>Logout success.</p>
                        {% endif %}
                    </div>
                </div>
            </section>
        </div>
    </main>

{% endblock %}

templates/users/signup.html
{% extends "base.html" %}
{% load i18n %}
{#{% load account socialaccount %}#}
{#{% load crispy_forms_tags %}#}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
    <main style="height: 80%">
        <div class="container">
            <section class="mb-4">
                <div class="row wow fadeIn">
                    <div class='col-6 offset-3'>
                        <h1>{% trans "Sign up" %}</h1>
                        {% if request.user.is_authenticated %}
                            <p>You have logged in out system.</p>
                        {% else %}
                            <form class="signup" method="POST" action="{% url 'signup' %}">{% csrf_token %}
                                <div class="mb-3">
                                    <label for="signupInputUsername" class="form-label">Username</label>
                                    <input name="username" type="input" class="form-control" id="signupInputUsername">
                                </div>
                                <div class="mb-3">
                                    <label for="signupInputEmail" class="form-label">Email address</label>
                                    <input name="email" type="email" class="form-control has-validation"
                                           id="signupInputEmail"
                                           aria-describedby="emailHelp">
                                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="signupInputPhone" class="form-label">Phone</label>
                                    <input name="phone" type="tel" class="form-control" id="signupInputPhone"
                                           aria-describedby="phoneHelp">
                                    <div id="phoneHelp" class="form-text">We'll never share your phone with anyone else.
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="signupInputPwd" class="form-label">Password</label>
                                    <input name="password" type="password" class="form-control" id="signupInputPwd">
                                </div>
                                <button class="btn btn-primary" type="submit">{% trans "Sign up" %}</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </section>
        </div>
    </main>

{% endblock %}